fair_counts_main_homepage:
    pattern:  /
    defaults: { _controller: FairCountsMainBundle:Default:index }

fair_counts_main_welcome:
    pattern:  /welcome
    defaults: { _controller: FairCountsMainBundle:Default:welcome }