fair_counts_user_homepage:
    pattern:  /user/{name}
    defaults: { _controller: FairCountsUserBundle:Default:index }

fair_counts_user_homagepage2:
    pattern:  /userTest/{name}
    defaults: { _controller: FairCountsUserBundle:Default:test }

fair_counts_user_homagepage3:
    pattern:  /createUser/{username}/{password}/{email}
    defaults: { _controller: FairCountsUserBundle:Default:addUser }

fair_counts_user_homagepage4:
    pattern:  /login/{username}/{password}/
    defaults: { _controller: FairCountsUserBundle:Default:login }

fair_counts_user_homagepage5:
    pattern:  /folders
    defaults: { _controller: FairCountsUserBundle:Default:getUserFolders }
