parameters:
#    fair_counts_user.example.class: FairCounts\UserBundle\Example

services:
#    fair_counts_user.example:
#        class: %fair_counts_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
