parameters:
#    fair_counts_user.example.class: FairCounts\UserBundle\Example

services:
    fair_counts_user.registration.form.type:
        class: FairCounts\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fair_counts_user_registration }
  
    fair_counts_user.password_changed:
        class: FairCounts\UserBundle\EventListener\PasswordChangedListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }

    fair_counts_user.password_reset:
        class: FairCounts\UserBundle\EventListener\PasswordResetListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }